FROM python:3.11-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y build-essential libpq-dev gcc libxml2-dev libxslt1-dev && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --upgrade pip
COPY requirements-web.txt .
COPY requirements-worker.txt .
RUN pip install -r requirements-web.txt && pip install -r requirements-worker.txt

CMD ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info", "--concurrency=4"]