FROM python:3.11-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y build-essential libpq-dev gcc libxml2-dev libxslt1-dev && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --upgrade pip
# install only web requirements for API image
COPY requirements-web.txt .
RUN pip install -r requirements-web.txt

EXPOSE 10000

CMD ["gunicorn", "app:app", "-w", "4", "-b", "0.0.0.0:10000"]